CREATE LOGICAL SOURCE endless(val UINT64 NOT NULL, ts UINT64);
CREATE PHYSICAL SOURCE FOR endless TYPE Generator SET(
    'ALL' as "SOURCE".STOP_GENERATOR_WHEN_SEQUENCE_FINISHES,
    'CSV' as INPUT_FORMATTER."TYPE",
    'localhost:8080' as "SOURCE"."HOST",
    30000 as "SOURCE".MAX_RUNTIME_MS,
    'SEQUENCE UINT32 0 10000000 1, SEQUENCE UINT64 0 10000000 1' AS "SOURCE".GENERATOR_SCHEMA);
CREATE WORKER 'localhost:8080' SET ('localhost:9090' AS DATA);

SELECT VAL, TS, VAL + TS AS VAL2 FROM ENDLESS
    INTO File(
   'CSV' as "SINK".OUTPUT_FORMAT,
   'test.txt' as "SINK".FILE_PATH,
   'localhost:8080' AS "SINK"."HOST"
);