CREATE LOGICAL SOURCE endless1(val1 UINT64 NOT NULL, ts1 UINT64);
CREATE PHYSICAL SOURCE FOR endless1 TYPE Generator SET(
    'ALL' as "SOURCE".STOP_GENERATOR_WHEN_SEQUENCE_FINISHES,
    'CSV' as INPUT_FORMATTER."TYPE",
    'localhost:8080' as "SOURCE"."HOST",
    3000000 as "SOURCE".MAX_RUNTIME_MS,
    'SEQUENCE UINT32 0 10000000 1, SEQUENCE UINT64 0 10000000 1' AS "SOURCE".GENERATOR_SCHEMA);

CREATE LOGICAL SOURCE endless2(val2 UINT64 NOT NULL, ts2 UINT64);
CREATE PHYSICAL SOURCE FOR endless2 TYPE Generator SET(
    'ALL' as "SOURCE".STOP_GENERATOR_WHEN_SEQUENCE_FINISHES,
    'CSV' as INPUT_FORMATTER."TYPE",
    'localhost:8080' as "SOURCE"."HOST",
    3000000 as "SOURCE".MAX_RUNTIME_MS,
    'SEQUENCE UINT32 0 10000000 1, SEQUENCE UINT64 0 10000000 1' AS "SOURCE".GENERATOR_SCHEMA);


CREATE WORKER 'localhost:8080' SET ('localhost:9090' AS DATA);

SELECT *
FROM (
    SELECT *
    FROM endless1)
JOIN (
    SELECT *
    FROM endless2)
ON (val1 = val2)
WINDOW TUMBLING (ts1, ts2, size 1 sec)
INTO File(
    'CSV' as "SINK".OUTPUT_FORMAT,
    'test.txt' as "SINK".FILE_PATH,
    'localhost:8080' AS "SINK"."HOST"
);

SHOW QUERIES;
